POST http://localhost:8000/registro/
Content-Type: application/json

{
    "correo": "paco1@example.com",
    "nombre": "Paco",
    "sexo": "Male",
    "nacimiento": "1985-03-10",
    "contrasegna": "Lojusto2",
    "pais": "Mexico"
}