# Generated by Django 5.0.2 on 2024-03-02 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('puntuacion', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('nombre', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('publica', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('presentadores', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('correo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('sexo', models.CharField(blank=True, max_length=255)),
                ('nacimiento', models.DateField(blank=True, null=True)),
                ('contrasegna', models.CharField(max_length=255)),
                ('pais', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('letra', models.CharField(max_length=255)),
                ('cantantes', models.CharField(max_length=255)),
                ('miAlbum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Musify.album')),
            ],
        ),
        migrations.CreateModel(
            name='Pertenecen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('miAudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Musify.audio')),
                ('miGenero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Musify.genero')),
            ],
        ),
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('miPodcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitulos', to='Musify.podcast')),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('miAudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veces_escuchado', to='Musify.audio')),
                ('miUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_escucha', to='Musify.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Cola',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('miAudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Musify.audio')),
                ('miUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Musify.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Contiene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miAudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists_que_lo_contienen', to='Musify.audio')),
                ('miPlaylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios_contenidos', to='Musify.playlist')),
            ],
            options={
                'unique_together': {('miAudio', 'miPlaylist')},
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miAudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veces_marcado_favorito', to='Musify.audio')),
                ('miUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios_favoritos', to='Musify.usuario')),
            ],
            options={
                'unique_together': {('miUsuario', 'miAudio')},
            },
        ),
        migrations.CreateModel(
            name='Colabora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miPlaylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='Musify.playlist')),
                ('miUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists_colaboradas', to='Musify.usuario')),
            ],
            options={
                'unique_together': {('miUsuario', 'miPlaylist')},
            },
        ),
        migrations.CreateModel(
            name='Amigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('micorreo1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amigos1', to='Musify.usuario')),
                ('micorreo2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amigos2', to='Musify.usuario')),
            ],
            options={
                'unique_together': {('micorreo1', 'micorreo2')},
            },
        ),
    ]
