# Generated by Django 5.0.2 on 2024-03-05 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musify', '0002_alter_cola_miaudio_alter_favorito_miaudio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='miAlbum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Musify.album'),
        ),
    ]
