# Generated by Django 5.0.2 on 2024-03-09 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musify', '0003_alter_cancion_mialbum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cantante',
            fields=[
                ('nombre', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='cancion',
            name='letra',
        ),
        migrations.AlterField(
            model_name='cancion',
            name='cantantes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Musify.cantante'),
        ),
    ]
