# Generated by Django 5.0.2 on 2024-04-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musify', '0007_cancion_archivo_mp3_cancion_foto_capitulo_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
