# Generated by Django 5.0.2 on 2024-04-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musify', '0008_alter_capitulo_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='favorito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='podcast',
            name='favorito',
            field=models.BooleanField(default=False),
        ),
    ]
