# Generated by Django 5.0.2 on 2024-04-19 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musify', '0009_cancion_favorito_podcast_favorito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancion',
            name='cantantes',
        ),
        migrations.AlterUniqueTogether(
            name='pertenecen',
            unique_together={('miGenero', 'miAudio')},
        ),
        migrations.CreateModel(
            name='Cantan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('miArtista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Musify.artista')),
                ('miCancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Musify.cancion')),
            ],
            options={
                'unique_together': {('miArtista', 'miCancion')},
            },
        ),
    ]
