# Generated by Django 5.0.2 on 2024-04-19 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musify', '0010_remove_cancion_cantantes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancion',
            name='favorito',
        ),
    ]
