# Generated by Django 5.0.2 on 2024-04-20 15:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musify', '0012_usuario_is_active_usuario_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
