# Generated by Django 5.0.2 on 2024-04-20 16:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musify', '0013_customtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtoken',
            name='key',
            field=models.CharField(default=uuid.uuid4, max_length=40, primary_key=True, serialize=False),
        ),
    ]
