# Generated by Django 5.0.2 on 2024-04-22 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musify', '0014_alter_customtoken_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='numPuntuaciones',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='numPuntuaciones',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='puntuacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PuntuaCancion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('puntuacion', models.IntegerField()),
                ('miCancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Musify.cancion')),
                ('miUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PuntuaPodcast',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('puntuacion', models.IntegerField()),
                ('miPodcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Musify.podcast')),
                ('miUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
