# Generated by Django 5.0.2 on 2024-04-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musify', '0015_cancion_numpuntuaciones_podcast_numpuntuaciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntuapodcast',
            name='miPodcast',
        ),
        migrations.RemoveField(
            model_name='puntuapodcast',
            name='miUsuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='artistas_favoritos',
            field=models.ManyToManyField(related_name='artistas_favoritos', to='Musify.artista'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='generos_favoritos',
            field=models.ManyToManyField(related_name='generos_favoritos', to='Musify.genero'),
        ),
        migrations.DeleteModel(
            name='PuntuaCancion',
        ),
        migrations.DeleteModel(
            name='PuntuaPodcast',
        ),
    ]
