# Generated by Django 5.0.2 on 2024-04-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musify', '0017_presentador_rename_archivo_mp3_cancion_archivomp3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
