# Generated by Django 5.0.2 on 2024-04-23 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musify', '0018_usuario_is_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguidores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miUsuario2', to=settings.AUTH_USER_MODEL)),
                ('seguidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('miUsuario', 'seguidor')},
            },
        ),
        migrations.CreateModel(
            name='Seguidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miUsuario', to=settings.AUTH_USER_MODEL)),
                ('seguido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguido', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('miUsuario', 'seguido')},
            },
        ),
    ]
