# Generated by Django 5.0.2 on 2024-04-23 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musify', '0019_seguidores_seguidos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seguidos',
            new_name='Seguido',
        ),
        migrations.RenameModel(
            old_name='Seguidores',
            new_name='Seguidor',
        ),
    ]
