# Generated by Django 5.0.2 on 2024-04-27 15:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musify', '0024_usuario_ultima_cancion_usuario_ultima_minutos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=10000)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('miUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('miSala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Musify.sala')),
            ],
        ),
    ]
