# Generated by Django 5.0.2 on 2024-04-27 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musify', '0026_customlogentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomLogEntry',
        ),
    ]
