# Generated by Django 5.0.2 on 2024-04-29 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musify', '0027_delete_customlogentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensaje',
            options={'ordering': ['fecha']},
        ),
    ]
