# Generated by Django 5.0.2 on 2024-04-29 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musify', '0028_alter_mensaje_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguido',
            name='miUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miUsuario_seguido', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seguidor',
            name='miUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miUsuario_seguidor', to=settings.AUTH_USER_MODEL),
        ),
    ]
