# Generated by Django 5.0.2 on 2024-04-29 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musify', '0029_alter_seguido_miusuario_alter_seguidor_miusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguido',
            name='miUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miUsuarioSeguido', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seguidor',
            name='miUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miUsuarioSeguidor', to=settings.AUTH_USER_MODEL),
        ),
    ]
