# Generated by Django 5.0.2 on 2024-04-29 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musify', '0030_alter_seguido_miusuario_alter_seguidor_miusuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seguido',
            old_name='miUsuario',
            new_name='miUsuarioSeguido',
        ),
        migrations.RenameField(
            model_name='seguidor',
            old_name='miUsuario',
            new_name='miUsuarioSeguidor',
        ),
        migrations.AlterUniqueTogether(
            name='seguido',
            unique_together={('miUsuarioSeguido', 'seguido')},
        ),
        migrations.AlterUniqueTogether(
            name='seguidor',
            unique_together={('miUsuarioSeguidor', 'seguidor')},
        ),
    ]
