# Generated by Django 5.0.2 on 2024-05-02 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musify', '0035_usuario_artistafavorito_usuario_generofavorito1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='generoFavorito1',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='generoFavorito2',
        ),
        migrations.AddField(
            model_name='genero',
            name='tipo',
            field=models.CharField(default='Cancion', max_length=255),
        ),
        migrations.AddField(
            model_name='usuario',
            name='generoFavoritoCancion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generoFavoritoCancion', to='Musify.genero'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='generoFavoritoPodcast',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generoFavoritoPodcast', to='Musify.genero'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='presentadorFavorito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presentadorFavorito', to='Musify.presentador'),
        ),
    ]
