# Generated by Django 5.0.2 on 2024-05-10 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musify', '0038_alter_mensaje_fecha'),
    ]

    operations = [
    ]
