# Generated by Django 5.0.2 on 2024-05-11 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musify', '0040_historial_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancion',
            name='archivoMp3',
        ),
    ]
